In [1]:
import numpy as np
import pandas as pd
import datetime
import random
import itertools as it


#Gather User-Input
year = input("Enter Year: ")
month = input("Enter Month: ")
day = input("Enter Day: ")
td = input("Days Between Games: ")
nTeams = input("Enter Number of Teams: ")
nGames = nTeams

#Turn Str values to Int values
year = int(year)
month = int(month)
day = int(day)
bd = int(td)
nGames = int(nGames)
nTeams = int(nTeams)

#Use the User-Input to create the Starting Date (sd)
sd = datetime.date(year,month,day)

#Display the Start Date and Number of Games
print('Start Date:',sd)
print('Number of Games:',nGames)

#Use User-Input to create a timedelta variable for Days Between Games
tdelta = datetime.timedelta(days=bd)

#User-Input ALL teams
tms = []
while len(tms)<nTeams:
    add_team = input("Add Team: ")
    tms.append(add_team)

Enter Year: 2019
Enter Month: 6
Enter Day: 14
Days Between Games: 7
Enter Number of Teams: 10
Start Date: 2019-06-14
Number of Games: 10
Add Team: Team 1
Add Team: Team 2
Add Team: Team 3
Add Team: Team 4
Add Team: Team 5
Add Team: Team 6
Add Team: Team 7
Add Team: Team 8
Add Team: Team 9
Add Team: Team 10

In [2]:
#Adding ALL Game Dates into 'd' variable
import math as math

d = []
gamesPerWeek = math.floor(nTeams/2)
gamesPerWeek = int(gamesPerWeek)
totalGames = gamesPerWeek*nGames
totalGames = int(totalGames)

def game_dates():
    while len(d)<nGames:
        add_game = sd+(tdelta*len(d))
        d.append(add_game)

for _ in range(gamesPerWeek):
    game_dates()

d

[datetime.date(2019, 6, 14),
 datetime.date(2019, 6, 21),
 datetime.date(2019, 6, 28),
 datetime.date(2019, 7, 5),
 datetime.date(2019, 7, 12),
 datetime.date(2019, 7, 19),
 datetime.date(2019, 7, 26),
 datetime.date(2019, 8, 2),
 datetime.date(2019, 8, 9),
 datetime.date(2019, 8, 16)]

In [3]:
from itertools import combinations

pairings = list(it.permutations(tms,2))

In [4]:
#use to randomize home and away
from random import shuffle

newpairs = [(i) for i in pairings]
finalpairs = random.sample(newpairs, k=totalGames)

finalpairs

[('Team 1', 'Team 10'),
 ('Team 4', 'Team 7'),
 ('Team 5', 'Team 1'),
 ('Team 3', 'Team 5'),
 ('Team 1', 'Team 2'),
 ('Team 10', 'Team 2'),
 ('Team 6', 'Team 1'),
 ('Team 2', 'Team 1'),
 ('Team 4', 'Team 2'),
 ('Team 9', 'Team 5'),
 ('Team 1', 'Team 4'),
 ('Team 6', 'Team 10'),
 ('Team 4', 'Team 10'),
 ('Team 5', 'Team 8'),
 ('Team 10', 'Team 9'),
 ('Team 2', 'Team 6'),
 ('Team 7', 'Team 1'),
 ('Team 9', 'Team 1'),
 ('Team 7', 'Team 10'),
 ('Team 3', 'Team 9'),
 ('Team 7', 'Team 9'),
 ('Team 1', 'Team 5'),
 ('Team 3', 'Team 6'),
 ('Team 10', 'Team 3'),
 ('Team 6', 'Team 3'),
 ('Team 3', 'Team 7'),
 ('Team 10', 'Team 1'),
 ('Team 9', 'Team 10'),
 ('Team 1', 'Team 7'),
 ('Team 6', 'Team 4'),
 ('Team 2', 'Team 3'),
 ('Team 10', 'Team 7'),
 ('Team 3', 'Team 4'),
 ('Team 1', 'Team 6'),
 ('Team 5', 'Team 10'),
 ('Team 2', 'Team 4'),
 ('Team 3', 'Team 10'),
 ('Team 3', 'Team 2'),
 ('Team 9', 'Team 6'),
 ('Team 4', 'Team 6'),
 ('Team 8', 'Team 9'),
 ('Team 5', 'Team 9'),
 ('Team 7', 'Team 6'),
 ('Team 5', 'Team 3'),
 ('Team 5', 'Team 2'),
 ('Team 8', 'Team 10'),
 ('Team 2', 'Team 10'),
 ('Team 2', 'Team 7'),
 ('Team 2', 'Team 5'),
 ('Team 6', 'Team 9')]

In [5]:
tmsH = []
while len(tmsH)<totalGames:
    add_HomeTeam = finalpairs[len(tmsH)][0]
    tmsH.append(add_HomeTeam)
    
tmsA = []
while len(tmsA)<totalGames:
    add_AwayTeam = finalpairs[len(tmsA)][1]
    tmsA.append(add_AwayTeam)

In [6]:
#SCHEDULE GENERATOR    
from random import shuffle

gameList = list(range(1,(totalGames+1)))

#Generate Schedule
schedule = pd.DataFrame({'Date': (d * gamesPerWeek), 'Home': (tmsH), 'Away': (tmsA)})
schedule.sort_values(by=['Date'], inplace=True, ascending=True)
schedule.index = gameList
schedule

          Date     Home     Away
1   2019-06-14   Team 1  Team 10
2   2019-06-14   Team 2   Team 3
3   2019-06-14   Team 7   Team 9
4   2019-06-14   Team 8   Team 9
5   2019-06-14   Team 1   Team 4
6   2019-06-21   Team 1   Team 5
7   2019-06-21   Team 5   Team 9
8   2019-06-21   Team 6  Team 10
9   2019-06-21   Team 4   Team 7
10  2019-06-21  Team 10   Team 7
11  2019-06-28   Team 7   Team 6
12  2019-06-28   Team 3   Team 6
13  2019-06-28   Team 5   Team 1
14  2019-06-28   Team 4  Team 10
15  2019-06-28   Team 3   Team 4
16  2019-07-05  Team 10   Team 3
17  2019-07-05   Team 5   Team 3
18  2019-07-05   Team 3   Team 5
19  2019-07-05   Team 1   Team 6
20  2019-07-05   Team 5   Team 8
21  2019-07-12   Team 5   Team 2
22  2019-07-12   Team 5  Team 10
23  2019-07-12   Team 6   Team 3
24  2019-07-12   Team 1   Team 2
25  2019-07-12  Team 10   Team 9
26  2019-07-19  Team 10   Team 2
27  2019-07-19   Team 3   Team 7
28  2019-07-19   Team 2   Team 4
29  2019-07-19   Team 8  Team 10
30  2019-07-19   Team 2   Team 6
31  2019-07-26   Team 3  Team 10
32  2019-07-26   Team 7   Team 1
33  2019-07-26   Team 2  Team 10
34  2019-07-26  Team 10   Team 1
35  2019-07-26   Team 6   Team 1
36  2019-08-02   Team 9   Team 1
37  2019-08-02   Team 9  Team 10
38  2019-08-02   Team 2   Team 7
39  2019-08-02   Team 3   Team 2
40  2019-08-02   Team 2   Team 1
41  2019-08-09   Team 7  Team 10
42  2019-08-09   Team 9   Team 6
43  2019-08-09   Team 1   Team 7
44  2019-08-09   Team 2   Team 5
45  2019-08-09   Team 4   Team 2
46  2019-08-16   Team 4   Team 6
47  2019-08-16   Team 3   Team 9
48  2019-08-16   Team 9   Team 5
49  2019-08-16   Team 6   Team 4
50  2019-08-16   Team 6   Team 9

In [ ]:
schedule.to_csv('schedule_example.csv')